const CONFIG={discordUrl:"https://discord.gg/",siteUrl:"#",tips:["Observe les pièges avant de foncer.","Les meilleurs temps viennent surtout de la connaissance de la map.","Un freerun n'est actif que si tous les Deaths l'acceptent à temps.","Utilise le mode spectateur pour apprendre les passages difficiles."]};
const state={map:"deathrun_atomic_warfare",max:32,current:12,filesTotal:0,filesNeeded:0};const $=id=>document.getElementById(id);
function setProgress(v){v=Math.max(0,Math.min(100,v));$("progress-bar").style.width=v+"%";$("progress-value").textContent=Math.round(v)+"%"}
function setMap(map){state.map=map||state.map;$("map-name").textContent=state.map;$("map-image").src=`assets/maps/${state.map}.jpg`;$("map-image").onerror=()=>{$("map-image").src="assets/map-placeholder.svg";$("map-image").onerror=null}}
window.GameDetails=function(servername,serverurl,mapname,maxplayers,steamid,gamemode){if(mapname)setMap(mapname);if(maxplayers)$("players-max").textContent=maxplayers;if(gamemode)$("gamemode-name").textContent=gamemode};
window.SetFilesTotal=function(total){state.filesTotal=Number(total)||0};window.SetFilesNeeded=function(needed){state.filesNeeded=Number(needed)||0;if(state.filesTotal>0)setProgress(((state.filesTotal-state.filesNeeded)/state.filesTotal)*100)};
window.DownloadingFile=function(name){$("loading-file").textContent=name?`Téléchargement : ${name}`:"Téléchargement..."};window.SetStatusChanged=function(status){$("status-text").textContent=(status||"CONNEXION EN COURS").toUpperCase();if(/sending client info/i.test(status||""))setProgress(100)};
$("discord-link").href=CONFIG.discordUrl;$("site-link").href=CONFIG.siteUrl;$("tip-text").textContent=CONFIG.tips[Math.floor(Math.random()*CONFIG.tips.length)];$("players-current").textContent=state.current;setMap(state.map);
let demo=0;const t=setInterval(()=>{demo+=1.5;setProgress(demo);if(demo>=100){clearInterval(t);$("status-text").textContent="PRÊT À REJOINDRE";$("loading-file").textContent="Chargement terminé"}},120);
